---

# Create space for project scripts in /opt
- name: Create /opt/metanyx
  file: path=/opt/metanyx/bin state=directory owner=root group=root mode=0700

# Set up networking
- name: Install networking interfaces config
  template: 
    src: interfaces.j2 
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0600
  notify: 
    - ifdown ext_interface
    - Restart networking
    - ifup ext_interface
    - ifup int_interface

- name: Install the MVPS hosts file to blackhole advertisers and stink sites
  copy: src=mvps_hosts.txt dest=/etc/mvps_hosts owner=root group=root mode=0644

- name: Set up DHCP client config
  template: src=dhclient.j2 dest=/etc/dhcp/dhclient.conf owner=root group=root mode=0644

- name: Set up resolv.conf for DNS resolution
  template: src=resolv.j2 dest=/etc/resolv.conf owner=root group=root mode=0644

# Packages required/useful for ansible use of apt
- name: Ensure apt dependencies are installed
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - python-apt
    - apt-transport-https

# Update repository cache
- name: Update apt cache
  apt: update_cache=yes

# Remove unused packages
- name: Remove unwanted applications
  apt:
    pkg: "{{ item }}"
    state: absent
    purge: yes
  with_items:
    - lightdm
    - apache2.2-bin
    - apache2-utilsA
    - wicd-daemon
    - wicd-cli
    - wicd-curses
    - wicd-gtk
    - python-wicd

# System tools
- name: Install useful system tools
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - vim
    - lsof
    - htop
    - tmux
    - wavemon

# Networking applications
- name: Install networking applications
  apt:
    pkg: "{{ item}}"
    state: latest
  with_items:
    - hostapd
    - dnsmasq
    - macchanger
    - usb-modeswitch

# Security tools
- name: Install security related applications
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - cryptsetup
    - iptables
    - iptables-persistent
    - macchanger

# Set up hostapd binaries
- name: Copy hostapd binaries
  copy: src={{ item }}_olimex dest=/opt/metanyx/bin/{{ item }} owner=root group=root mode=0754
  with_items:
    - hostapd_nl80211
    - hostapd_rtl8188
- name: Link hostapd binary
  file: path=/usr/sbin/hostapd src=/opt/metanyx/bin/hostapd_rtl8188 force=yes state=link

# Set up DHCP on eth0
- name: Set up configuration script for dnsmasq
  template: src=dnsmasq.j2 dest=/etc/dnsmasq.conf owner=root group=root mode=0644
  notify: Reload dnsmasq

# Set up Hostapd config for Access Point
- name: Create hostapd.conf
  template: 
    src: hostapd_conf.j2 
    dest: /etc/hostapd/hostapd.conf
    owner: root
    group: root
    mode: 0600
- name: Copy hostapd default config
  copy: src=hostapd_default dest=/etc/default/hostapd owner=root group=root mode=0644
  notify: Restart hostapd

# Install tor
- name: Install TOR
  apt: pkg=tor state=latest
- name: Set up torrc configuration file
  template: src=torrc.j2 dest=/etc/tor/torrc owner=root group=root mode=0644

# Set up iptables rules and service
- name: Install iptables rules
  template: src=iptables.j2 dest=/root/iptables.sh owner=root group=root mode=0700
  notify: Load iptables rules
- name: Start iptables-persistent
  service: name=iptables-persistent enabled=yes
