---

# Create space for project scripts in /opt
- name: Create /opt/metanyx
  file: path=/opt/metanyx state=directory owner=root group=root mode=0700

# Set up networking
- name: Install networking interfaces config
  template: 
    src: interfaces.j2 
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0600
  notify: 
    - ifdown ext_interface
    - Restart networking
    - ifup ext_interface
    - ifup int_interface

- name: Install the MVPS hosts file to blackhole advertisers and stink sites
  copy: src=mvps_hosts.txt dest=/etc/mvps_hosts owner=root group=root mode=0644

- name: Set up DHCP client config
  template: src=dhclient.j2 dest=/etc/dhcp/dhclient.conf owner=root group=root mode=0644

- name: Set up resolv.conf for DNS resolution
  template: src=resolv.j2 dest=/etc/resolv.conf owner=root group=root mode=0644

# Packages required/useful for ansible use of apt
- name: Ensure apt dependencies are installed
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - python-apt
    - apt-transport-https

# Update repository cache
- name: Update apt cache
  apt: update_cache=yes

# Remove unused packages
- name: Remove unwanted applications
  apt:
    pkg: "{{ item }}"
    state: absent
    purge: yes
  with_items:
    - lightdm
    - apache2.2-bin
    - apache2-utilsA
    - wicd-daemon
    - wicd-cli
    - wicd-curses
    - wicd-gtk
    - python-wicd

# System tools
- name: Install useful system tools
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - vim
    - lsof
    - htop
    - tmux
    - wavemon

# Security tools
- name: Install security related applications
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - cryptsetup
    - iptables
    - iptables-persistent
    - macchanger

# Turn off X
- name: Disable graphical environment
  service:
    name: multi-user.target
    state: started
    enabled: yes

# Disable packaged BeagleBone web services
#- name: Disable default BeagleBone web services
#  service:
#    name: "{{ item }}"
#    state: stopped
#    enabled: no
#  with_items:
#    - cloud9.service
#    - bonescript-autorun.service
#    - bonescript.socket
#    - bonescript.service

# Disable packaged BeagleBone web services
- name: Disable default BeagleBone web services
  command: systemctl disable --ignore-dependencies -f "{{ item }}"
  with_items:
    - cloud9.service
    - cloud9.socket
    - bonescript.service
    - bonescript.socket
    - bonescript-autorun.service

- name: Remove default Beaglebone web services
  command: 'rm -f /lib/systemd/system/"{{ item }}"'
  with_items:
    - cloud9.service
    - cloud9.socket
    - bonescript.service
    - bonescript.socket
    - bonescript-autorun.service

# Set up DHCP on eth0
- name: Install dnsmasq for dhcp on client-side interfaces
  apt: pkg=dnsmasq state=latest
- name: Set up configuration script for dnsmasq
  template: src=dnsmasq.j2 dest=/etc/dnsmasq.conf owner=root group=root mode=0644
  notify: Reload dnsmasq

# Install tor
- name: Install TOR
  apt: pkg=tor state=latest
- name: Set up torrc configuration file
  template: src=torrc.j2 dest=/etc/tor/torrc owner=root group=root mode=0644
#  notify: Restart tor

# Set up iptables rules and service
- name: Install iptables rules
  template: src=iptables.j2 dest=/root/iptables.sh owner=root group=root mode=0700
  notify: Load iptables rules

- name: Start iptables-persistent
  service: name=iptables-persistent enabled=yes
