---

- name: Load iptables rules
  command: /bin/bash /root/iptables.sh

- name: Reload networking
  service: name=networking enabled=yes state=reloaded

- name: Reload dnsmasq
  service: name=dnsmasq enabled=yes state=reloaded

- name: Restart tor
  service: name=tor enabled=yes state=restarted
