---

- name: Load iptables rules
  command: /bin/bash /root/iptables.sh

- name: Restart networking
  service: name=networking enabled=yes state=restarted

- name: ifdown ext_interface
  command: ifdown {{ external_interface }}

- name: ifup ext_interface
  command: ifup {{ external_interface }}

- name: ifup int_interface
  command: ifup eth0

- name: Restart dnsmasq
  service: name=dnsmasq enabled=yes state=restarted

- name: Restart hostapd
  service: name=hostapd enabled=yes state=restarted

- name: Restart tor
  service: name=tor enabled=yes state=restarted
