---

- name: Clone the webmanager repo
  git: repo=https://github.com/metanyx/metanyx-manager.git dest=/tmp/metanyx-manager

- name: Install webmanager
  command: bash /tmp/metanyx-manager/install.sh

- name: Remove webmanager repo
  command: rm -rf /tmp/metanyx-manager
